### ISSUE TITLE
Error in metaSNV.py while running `motus snv_call`

### ISSUE THREAD

**Issue by mikemc** [motu-tool/mOTUs#26]
I installed mOTUs2 via `conda install -c bioconda motus`. After running `motus map_snv` on a set of 18 metagenomes, I ran `motus snv_call` and got the following error log (truncated for brevity; let me know if you want more info). I haven't had a chance to dig into what might be going wrong yet, but will try to poke around some.
```
metaSNV.py /home/mrmclare/data/mgs_bias/costea2017/motus2/snvs /home/mrmclare/data/mgs_bias/costea2017/motus2/bam/sample_list /home/mrmclare/applications/miniconda3/envs/motus/share/motus-2.1.1/db_mOTU/mOTU.v    2b.centroids.reformatted.padded --db_ann /home/mrmclare/applications/miniconda3/envs/motus/share/motus-2.1.1/db_mOTU/mOTU.v2b.centroids.reformatted.padded.annotations --threads 16 --n_splits 16               
Printing details in /home/mrmclare/data/mgs_bias/costea2017/motus2/snvs/cov/ERR1539476.bam.cov.detail!
(...)
Found 7727 genomes
16

Coverage summary here: /home/mrmclare/data/mgs_bias/costea2017/motus2/snvs
    Average vertical genome coverage: '/home/mrmclare/data/mgs_bias/costea2017/motus2/snvs/snvs.all_cov.tab'
    Horizontal genome coverage (1X): '/home/mrmclare/data/mgs_bias/costea2017/motus2/snvs/snvs.all_perc.tab'

Calculating best database split:
[mpileup] 18 samples in 18 input files  
(...)
Genomes loaded!
Traceback (most recent call last):
  File "/home/mrmclare/applications/miniconda3/envs/motus/bin/../share/metasnv-1.0.3//metaSNV.py", line 273, in <module>
    main()
  File "/home/mrmclare/applications/miniconda3/envs/motus/bin/../share/metasnv-1.0.3//metaSNV.py", line 270, in main
    snp_call(args)
  File "/home/mrmclare/applications/miniconda3/envs/motus/bin/../share/metasnv-1.0.3//metaSNV.py", line 209, in snp_call
    if v > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by hjruscheweyh** [comment]
Hi Michael
Thank you very much for the feedback. I assigned this issue to Lucas. It seems to be a small python2 artefact. 

Hans

**Comment by mikemc** [comment]
Thanks for your quick response! Your suggested edits did indeed fix the issue.

**Comment by LucasPaoli** [comment]
Thanks for the feedback. This is issue will be closed once the new version of metaSNV is available on bioconda.
